/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.

import { Route as rootRouteImport } from './__root'
import { Route as IndexRouteImport } from './index'
import { Route as AuthenticatedRouteRouteImport } from './_authenticated/route'
import { Route as CadastroRouteImport } from './cadastro'
import { Route as CheckoutRouteImport } from './checkout'
import { Route as LoginRouteImport } from './login'
import { Route as PlanosRouteImport } from './planos'
import { Route as PrivacidadeRouteImport } from './privacidade'
import { Route as RecuperarSenhaRouteImport } from './recuperar-senha'
import { Route as TermosRouteImport } from './termos'
import { Route as AuthenticatedAppRouteRouteImport } from './_authenticated/app/route'
import { Route as AuthenticatedAppIndexRouteImport } from './_authenticated/app/index'
import { Route as RelatoriosRouteImport } from './app/relatorios'
import { Route as CatalogoRouteImport } from './app/catalogo'
import { Route as NotificacoesRouteImport } from './app/notificacoes'
import { Route as ConfiguracoesRouteImport } from './app/configuracoes'

const IndexRoute = IndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => rootRouteImport } as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({ id: '/_authenticated', getParentRoute: () => rootRouteImport } as any)
const CadastroRoute = CadastroRouteImport.update({ id: '/cadastro', path: '/cadastro', getParentRoute: () => rootRouteImport } as any)
const CheckoutRoute = CheckoutRouteImport.update({ id: '/checkout', path: '/checkout', getParentRoute: () => rootRouteImport } as any)
const LoginRoute = LoginRouteImport.update({ id: '/login', path: '/login', getParentRoute: () => rootRouteImport } as any)
const PlanosRoute = PlanosRouteImport.update({ id: '/planos', path: '/planos', getParentRoute: () => rootRouteImport } as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({ id: '/privacidade', path: '/privacidade', getParentRoute: () => rootRouteImport } as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({ id: '/recuperar-senha', path: '/recuperar-senha', getParentRoute: () => rootRouteImport } as any)
const TermosRoute = TermosRouteImport.update({ id: '/termos', path: '/termos', getParentRoute: () => rootRouteImport } as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({ id: '/app', path: '/app', getParentRoute: () => AuthenticatedRouteRoute } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({ id: '/', path: '/', getParentRoute: () => AuthenticatedAppRouteRoute } as any)
const RelatoriosRoute = RelatoriosRouteImport.update({ id: '/relatorios', path: '/relatorios', getParentRoute: () => AuthenticatedAppRouteRoute } as any)
const CatalogoRoute = CatalogoRouteImport.update({ id: '/catalogo', path: '/catalogo', getParentRoute: () => AuthenticatedAppRouteRoute } as any)
const NotificacoesRoute = NotificacoesRouteImport.update({ id: '/notificacoes', path: '/notificacoes', getParentRoute: () => AuthenticatedAppRouteRoute } as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({ id: '/configuracoes', path: '/configuracoes', getParentRoute: () => AuthenticatedAppRouteRoute } as any)

const authenticatedAppRouteChildren = {
  index: AuthenticatedAppIndexRoute,
  relatorios: RelatoriosRoute,
  catalogo: CatalogoRoute,
  notificacoes: NotificacoesRoute,
  configuracoes: ConfiguracoesRoute,
}
const authenticatedRouteChildren = {
  app: AuthenticatedAppRouteRoute._addFileChildren(authenticatedAppRouteChildren),
}
const routeTree = rootRouteImport._addFileChildren({
  index: IndexRoute,
  authenticated: AuthenticatedRouteRoute._addFileChildren(authenticatedRouteChildren),
  cadastro: CadastroRoute,
  checkout: CheckoutRoute,
  login: LoginRoute,
  planos: PlanosRoute,
  privacidade: PrivacidadeRoute,
  'recuperar-senha': RecuperarSenhaRoute,
  termos: TermosRoute,
})

export { routeTree }
