import { useMemo, useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Link, useNavigate } from "@tanstack/react-router";
import { Car, Contact, ReceiptText, Users, WalletCards, Wrench } from "lucide-react";
import { toast } from "sonner";
import { EntityPage } from "./EntityPage";
import { Field } from "./Field";
import { FormDialog } from "./FormDialog";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import type { Database } from "@/integrations/supabase/types";
import { formatCurrency, formatDate, parseCurrencyToCents } from "@/lib/format";
import { customersQuery, expensesQuery, maintenancesQuery, paymentsQuery, PERIODICITY_LABEL, rentalsQuery, subscriptionQuery, VEHICLE_STATUS_LABEL, vehiclesQuery } from "@/lib/queries";

type Table = keyof Database["public"]["Tables"];

function useInsert(table: Table, queryKey: string, after?: () => Promise<void> | void) {
  const client = useQueryClient();
  return useMutation({ mutationFn: async (values: Record<string, unknown>) => {
    const { data: auth } = await supabase.auth.getUser();
    if (!auth.user) throw new Error("Sua sessão expirou.");
    const { error } = await supabase.from(table).insert({ ...values, user_id: auth.user.id } as never);
    if (error) throw error;
    await after?.();
  }, onSuccess: () => { client.invalidateQueries({ queryKey: [queryKey] }); toast.success("Registro salvo."); }, onError: (error) => toast.error(error.message) });
}

function FormGrid({ children }: { children: React.ReactNode }) { return <div className="grid gap-4 sm:grid-cols-2">{children}</div>; }
function ListGrid({ children }: { children: React.ReactNode }) { return <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{children}</div>; }
function RecordCard({ title, subtitle, badge, children }: { title: string; subtitle?: string | null; badge?: string; children: React.ReactNode }) { return <article className="min-h-40 rounded-md border border-border bg-card p-5"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h2 className="truncate font-display font-semibold">{title}</h2>{subtitle && <p className="mt-1 truncate text-xs text-muted-foreground">{subtitle}</p>}</div>{badge && <Badge variant="outline">{badge}</Badge>}</div><div className="mt-5 space-y-2 text-sm text-muted-foreground">{children}</div></article>; }
function value(form: FormData, key: string) { return String(form.get(key) ?? "").trim(); }

export function VehiclesPage() {
  const query = useQuery(vehiclesQuery);
  const subscription = useQuery(subscriptionQuery);
  const navigate = useNavigate();
  const [open, setOpen] = useState(false);
  const mutation = useInsert("vehicles", "vehicles");
  function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const f = new FormData(event.currentTarget); mutation.mutate({ brand: value(f,"brand"), model: value(f,"model"), year: value(f,"year") ? Number(value(f,"year")) : null, plate: value(f,"plate") || null, category: value(f,"category") || null, mileage: value(f,"mileage") ? Number(value(f,"mileage")) : null, rental_price_cents: parseCurrencyToCents(value(f,"price")), rental_periodicity: value(f,"periodicity") || "semanal", status: value(f,"status") || "disponivel", description: value(f,"description") || null, show_in_catalog: true }, { onSuccess: () => setOpen(false) }); }
  const rows = query.data ?? [];
  const limit = subscription.data?.vehicle_limit ?? null;
  const atLimit = limit != null && rows.length >= limit;
  function handleAction() {
    if (atLimit) {
      toast.error(`Você atingiu o limite de ${limit} veículos do seu plano.`, { action: { label: "Fazer upgrade", onClick: () => navigate({ to: "/planos" }) } });
      return;
    }
    setOpen(true);
  }
  return <><EntityPage title="Seus carros" description="Status, valor e disponibilidade da sua frota em um só lugar." actionLabel="Cadastrar carro" onAction={handleAction} icon={Car} loading={query.isLoading} error={query.error} empty={!rows.length} emptyTitle="Nenhum carro cadastrado" emptyText="Cadastre seu primeiro carro para começar a controlar a frota.">
  {atLimit && (
    <div className="mb-5 flex flex-col gap-3 rounded-md border border-destructive/30 bg-destructive/5 p-4 sm:flex-row sm:items-center sm:justify-between">
      <p className="text-sm text-destructive">Você atingiu o limite de {limit} veículos do seu plano.</p>
      <button type="button" className="text-sm font-medium text-brand hover:underline" onClick={() => navigate({ to: "/planos" })}>Fazer upgrade</button>
    </div>
  )}
  <ListGrid>
  {rows.map((car) => (
    <Link key={car.id} to="/app/veiculos/$id" params={{ id: car.id }} className="block">
      <RecordCard title={`${car.brand} ${car.model}`} subtitle={[car.year, car.plate].filter(Boolean).join(" • ")} badge={VEHICLE_STATUS_LABEL[car.status]}>
        <p>{formatCurrency(car.rental_price_cents)} / {PERIODICITY_LABEL[car.rental_periodicity].toLowerCase()}</p>
        <p>{car.mileage ? `${car.mileage.toLocaleString("pt-BR")} km` : "Quilometragem não informada"}</p>
        <p>{car.vehicle_photos.length}/10 fotos</p>
      </RecordCard>
    </Link>
  ))}
</ListGrid></EntityPage><FormDialog open={open} onOpenChange={setOpen} title="Cadastrar carro" description="Adicione os dados principais. As fotos podem ser incluídas depois." onSubmit={submit} saving={mutation.isPending}><FormGrid><Field label="Marca" htmlFor="brand"><Input id="brand" name="brand" required /></Field><Field label="Modelo" htmlFor="model"><Input id="model" name="model" required /></Field><Field label="Ano" htmlFor="year"><Input id="year" name="year" type="number" min="1950" max="2100" /></Field><Field label="Placa" htmlFor="plate"><Input id="plate" name="plate" /></Field><Field label="Categoria" htmlFor="category"><Input id="category" name="category" placeholder="Hatch, SUV..." /></Field><Field label="Quilometragem" htmlFor="mileage"><Input id="mileage" name="mileage" type="number" min="0" /></Field><Field label="Valor do aluguel" htmlFor="price"><Input id="price" name="price" placeholder="0,00" /></Field><Field label="Periodicidade" htmlFor="periodicity"><NativeSelect name="periodicity" options={[["semanal","Semanal"],["quinzenal","Quinzenal"],["mensal","Mensal"],["personalizada","Personalizada"]]} /></Field><Field label="Status" htmlFor="status"><NativeSelect name="status" options={Object.entries(VEHICLE_STATUS_LABEL)} /></Field></FormGrid><Field label="Descrição" htmlFor="description"><Textarea id="description" name="description" /></Field></FormDialog></>;
}

export function CustomersPage() {
  const query = useQuery(customersQuery); const [open,setOpen]=useState(false); const mutation=useInsert("customers","customers");
  function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);mutation.mutate({name:value(f,"name"),cpf:value(f,"cpf")||null,whatsapp:value(f,"whatsapp")||null,email:value(f,"email")||null,address:value(f,"address")||null,notes:value(f,"notes")||null},{onSuccess:()=>setOpen(false)});}
  const rows=query.data??[]; return <><EntityPage title="Seus clientes" description="Contatos e informações essenciais, sem exigir CNPJ." actionLabel="Adicionar cliente" onAction={()=>setOpen(true)} icon={Users} loading={query.isLoading} error={query.error} empty={!rows.length} emptyTitle="Nenhum cliente cadastrado" emptyText="Adicione um cliente para criar seu primeiro aluguel."><ListGrid>{rows.map(c=><RecordCard key={c.id} title={c.name} subtitle={c.whatsapp||c.email}><p>{c.cpf?`CPF ${c.cpf}`:"CPF não informado"}</p><p>{c.address||"Endereço não informado"}</p></RecordCard>)}</ListGrid></EntityPage><FormDialog open={open} onOpenChange={setOpen} title="Adicionar cliente" description="Você não precisa informar CNPJ." onSubmit={submit} saving={mutation.isPending}><FormGrid><Field label="Nome" htmlFor="name"><Input id="name" name="name" required /></Field><Field label="CPF" htmlFor="cpf"><Input id="cpf" name="cpf" /></Field><Field label="WhatsApp" htmlFor="whatsapp"><Input id="whatsapp" name="whatsapp" /></Field><Field label="E-mail" htmlFor="email"><Input id="email" name="email" type="email" /></Field></FormGrid><Field label="Endereço" htmlFor="address"><Input id="address" name="address" /></Field><Field label="Observações" htmlFor="notes"><Textarea id="notes" name="notes" /></Field></FormDialog></>;
}

function NativeSelect({name,options,required=true}:{name:string;options:[string,string][];required?:boolean}) { return <select name={name} required={required} className="flex h-9 w-full rounded-md border border-input bg-background px-3 text-sm">{options.map(([v,l])=><option value={v} key={v}>{l}</option>)}</select>; }
function RelationSelect({name,options,placeholder}:{name:string;options:{id:string;label:string}[];placeholder:string}) { return <select name={name} required className="flex h-9 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="">{placeholder}</option>{options.map(o=><option key={o.id} value={o.id}>{o.label}</option>)}</select>; }

export function RentalsPage(){
 const query=useQuery(rentalsQuery), cars=useQuery(vehiclesQuery), customers=useQuery(customersQuery); const [open,setOpen]=useState(false); const client=useQueryClient();
 const mutation=useInsert("rentals","rentals",async()=>{await client.invalidateQueries({queryKey:["vehicles"]});});
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const vehicleId=value(f,"vehicle_id");mutation.mutate({vehicle_id:vehicleId,customer_id:value(f,"customer_id"),start_date:value(f,"start_date"),end_date:value(f,"end_date")||null,amount_cents:parseCurrencyToCents(value(f,"amount")),periodicity:value(f,"periodicity"),payment_day:value(f,"payment_day")?Number(value(f,"payment_day")):null,notes:value(f,"notes")||null},{onSuccess:async()=>{await supabase.from("vehicles").update({status:"alugado"}).eq("id",vehicleId);client.invalidateQueries({queryKey:["vehicles"]});setOpen(false);}});}
 const rows=query.data??[], available=(cars.data??[]).filter(c=>c.status==="disponivel"||c.status==="reservado"); return <><EntityPage title="Seus aluguéis" description="Acompanhe quem está com cada carro, valores e vencimentos." actionLabel="Novo aluguel" onAction={()=>setOpen(true)} icon={Contact} loading={query.isLoading} error={query.error} empty={!rows.length} emptyTitle="Nenhum aluguel ativo" emptyText="Selecione um cliente e um carro disponível para começar."><ListGrid>{rows.map(r=><RecordCard key={r.id} title={r.vehicles?`${r.vehicles.brand} ${r.vehicles.model}`:"Carro"} subtitle={r.customers?.name} badge={r.status}><p>{formatCurrency(r.amount_cents)} • {PERIODICITY_LABEL[r.periodicity]}</p><p>Início em {formatDate(r.start_date)}</p>{r.payment_day&&<p>Pagamento no dia {r.payment_day}</p>}</RecordCard>)}</ListGrid></EntityPage><FormDialog open={open} onOpenChange={setOpen} title="Novo aluguel" description="O carro será marcado como alugado." onSubmit={submit} saving={mutation.isPending}><Field label="Cliente" htmlFor="customer_id"><RelationSelect name="customer_id" placeholder="Selecione" options={(customers.data??[]).map(c=>({id:c.id,label:c.name}))}/></Field><Field label="Carro disponível" htmlFor="vehicle_id"><RelationSelect name="vehicle_id" placeholder="Selecione" options={available.map(c=>({id:c.id,label:`${c.brand} ${c.model}`}))}/></Field><FormGrid><Field label="Data inicial" htmlFor="start_date"><Input name="start_date" id="start_date" type="date" required /></Field><Field label="Data final (opcional)" htmlFor="end_date"><Input name="end_date" id="end_date" type="date" /></Field><Field label="Valor" htmlFor="amount"><Input name="amount" id="amount" placeholder="0,00" required /></Field><Field label="Periodicidade" htmlFor="periodicity"><NativeSelect name="periodicity" options={Object.entries(PERIODICITY_LABEL)} /></Field><Field label="Dia de pagamento" htmlFor="payment_day"><Input name="payment_day" id="payment_day" type="number" min="1" max="31" /></Field></FormGrid><Field label="Observações" htmlFor="notes"><Textarea name="notes" id="notes" /></Field></FormDialog></>;
}

export function PaymentsPage(){
 const query=useQuery(paymentsQuery), cars=useQuery(vehiclesQuery), customers=useQuery(customersQuery); const [open,setOpen]=useState(false),[filter,setFilter]=useState("todos"); const client=useQueryClient(); const mutation=useInsert("payments","payments");
 async function markPaid(id:string){const {error}=await supabase.from("payments").update({status:"pago",paid_at:new Date().toISOString().slice(0,10)}).eq("id",id);if(error)toast.error(error.message);else{toast.success("Pagamento recebido.");client.invalidateQueries({queryKey:["payments"]});}}
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);mutation.mutate({customer_id:value(f,"customer_id")||null,vehicle_id:value(f,"vehicle_id")||null,amount_cents:parseCurrencyToCents(value(f,"amount")),due_date:value(f,"due_date"),status:value(f,"status"),method:value(f,"method")||null,notes:value(f,"notes")||null},{onSuccess:()=>setOpen(false)});}
 const all=query.data??[],rows=filter==="todos"?all:all.filter(p=>p.status===filter); return <><EntityPage title="Seus pagamentos" description="Recebidos, pendentes, atrasados e cancelados com visão rápida." actionLabel="Registrar pagamento" onAction={()=>setOpen(true)} icon={WalletCards} loading={query.isLoading} error={query.error} empty={!all.length} emptyTitle="Nenhum pagamento registrado" emptyText="Registre uma cobrança ou recebimento da sua frota."><div className="mb-5 flex gap-2 overflow-x-auto">{["todos","pago","pendente","atrasado","cancelado"].map(s=><button key={s} onClick={()=>setFilter(s)} className={`rounded-md border px-3 py-2 text-xs capitalize ${filter===s?"border-brand text-brand":"border-border text-muted-foreground"}`}>{s}</button>)}</div><ListGrid>{rows.map(p=><RecordCard key={p.id} title={formatCurrency(p.amount_cents)} subtitle={p.customers?.name||p.vehicles&&`${p.vehicles.brand} ${p.vehicles.model}`} badge={p.status}><p>Vencimento {formatDate(p.due_date)}</p>{p.method&&<p>{p.method}</p>}{p.status!=="pago"&&p.status!=="cancelado"&&<button className="text-brand" onClick={()=>markPaid(p.id)}>Marcar como recebido</button>}</RecordCard>)}</ListGrid></EntityPage><FormDialog open={open} onOpenChange={setOpen} title="Registrar pagamento" description="Este registro não processa cobranças reais." onSubmit={submit} saving={mutation.isPending}><FormGrid><Field label="Cliente" htmlFor="customer_id"><RelationSelect name="customer_id" placeholder="Selecione" options={(customers.data??[]).map(c=>({id:c.id,label:c.name}))}/></Field><Field label="Carro" htmlFor="vehicle_id"><RelationSelect name="vehicle_id" placeholder="Selecione" options={(cars.data??[]).map(c=>({id:c.id,label:`${c.brand} ${c.model}`}))}/></Field><Field label="Valor" htmlFor="amount"><Input name="amount" id="amount" required /></Field><Field label="Vencimento" htmlFor="due_date"><Input name="due_date" id="due_date" type="date" required /></Field><Field label="Status" htmlFor="status"><NativeSelect name="status" options={[["pendente","Pendente"],["pago","Pago"],["atrasado","Atrasado"],["cancelado","Cancelado"]]} /></Field><Field label="Forma" htmlFor="method"><Input name="method" id="method" placeholder="Pix, dinheiro..." /></Field></FormGrid><Field label="Observações" htmlFor="notes"><Textarea name="notes" id="notes" /></Field></FormDialog></>;
}

export function MaintenancesPage(){const query=useQuery(maintenancesQuery),cars=useQuery(vehiclesQuery);const[open,setOpen]=useState(false);const mutation=useInsert("maintenances","maintenances");function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);mutation.mutate({vehicle_id:value(f,"vehicle_id"),type:value(f,"type"),date:value(f,"date"),mileage:value(f,"mileage")?Number(value(f,"mileage")):null,cost_cents:parseCurrencyToCents(value(f,"cost")),description:value(f,"description")||null,next_date:value(f,"next_date")||null,next_mileage:value(f,"next_mileage")?Number(value(f,"next_mileage")):null,notes:value(f,"notes")||null},{onSuccess:()=>setOpen(false)});}const rows=query.data??[];return <><EntityPage title="Manutenções" description="Histórico de serviços e próximos cuidados com seus carros." actionLabel="Nova manutenção" onAction={()=>setOpen(true)} icon={Wrench} loading={query.isLoading} error={query.error} empty={!rows.length} emptyTitle="Nenhuma manutenção registrada" emptyText="Registre serviços e programe o próximo cuidado."><ListGrid>{rows.map(m=><RecordCard key={m.id} title={m.type} subtitle={m.vehicles&&`${m.vehicles.brand} ${m.vehicles.model}`}><p>{formatDate(m.date)} • {formatCurrency(m.cost_cents)}</p>{m.next_date&&<p>Próxima em {formatDate(m.next_date)}</p>}</RecordCard>)}</ListGrid></EntityPage><FormDialog open={open} onOpenChange={setOpen} title="Nova manutenção" description="Registre o serviço e, se quiser, a próxima data." onSubmit={submit} saving={mutation.isPending}><Field label="Carro" htmlFor="vehicle_id"><RelationSelect name="vehicle_id" placeholder="Selecione" options={(cars.data??[]).map(c=>({id:c.id,label:`${c.brand} ${c.model}`}))}/></Field><FormGrid><Field label="Tipo" htmlFor="type"><NativeSelect name="type" options={["Óleo","Pneus","Freios","Bateria","Revisão","Mecânica","Elétrica","Lavagem","Outros"].map(v=>[v,v])}/></Field><Field label="Data" htmlFor="date"><Input name="date" id="date" type="date" required /></Field><Field label="Quilometragem" htmlFor="mileage"><Input name="mileage" id="mileage" type="number" /></Field><Field label="Valor" htmlFor="cost"><Input name="cost" id="cost" /></Field><Field label="Próxima data" htmlFor="next_date"><Input name="next_date" id="next_date" type="date" /></Field><Field label="Próxima quilometragem" htmlFor="next_mileage"><Input name="next_mileage" id="next_mileage" type="number" /></Field></FormGrid><Field label="Descrição" htmlFor="description"><Textarea name="description" id="description" /></Field></FormDialog></>}

export function ExpensesPage(){const query=useQuery(expensesQuery),cars=useQuery(vehiclesQuery);const[open,setOpen]=useState(false);const mutation=useInsert("expenses","expenses");function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);mutation.mutate({vehicle_id:value(f,"vehicle_id")||null,category:value(f,"category")||"Outros",amount_cents:parseCurrencyToCents(value(f,"amount")),date:value(f,"date"),description:value(f,"description")||null},{onSuccess:()=>setOpen(false)});}const rows=query.data??[],total=useMemo(()=>rows.reduce((s,e)=>s+e.amount_cents,0),[rows]);return <><EntityPage title="Despesas" description={`Total registrado: ${formatCurrency(total)}. Acompanhe os custos por carro.`} actionLabel="Nova despesa" onAction={()=>setOpen(true)} icon={ReceiptText} loading={query.isLoading} error={query.error} empty={!rows.length} emptyTitle="Nenhuma despesa registrada" emptyText="Registre custos para acompanhar a rentabilidade real."><ListGrid>{rows.map(e=><RecordCard key={e.id} title={formatCurrency(e.amount_cents)} subtitle={e.vehicles&&`${e.vehicles.brand} ${e.vehicles.model}`} badge={e.category}><p>{formatDate(e.date)}</p><p>{e.description||"Sem descrição"}</p></RecordCard>)}</ListGrid></EntityPage><FormDialog open={open} onOpenChange={setOpen} title="Nova despesa" description="Vincule a um carro para calcular sua rentabilidade." onSubmit={submit} saving={mutation.isPending}><Field label="Carro (opcional)" htmlFor="vehicle_id"><select name="vehicle_id" className="flex h-9 w-full rounded-md border border-input bg-background px-3 text-sm"><option value="">Sem vínculo</option>{(cars.data??[]).map(c=><option value={c.id} key={c.id}>{c.brand} {c.model}</option>)}</select></Field><FormGrid><Field label="Categoria" htmlFor="category"><Input name="category" id="category" placeholder="Combustível, impostos..." required /></Field><Field label="Valor" htmlFor="amount"><Input name="amount" id="amount" required /></Field><Field label="Data" htmlFor="date"><Input name="date" id="date" type="date" required /></Field></FormGrid><Field label="Descrição" htmlFor="description"><Textarea name="description" id="description" /></Field></FormDialog></>}
